### ISSUE TITLE
TODO for milestone 3

### ISSUE THREAD

**Issue by applepiofmyeye** [applepiofmyeye/NUSWhere#12]
- [x] create routes page after clicking directions [priority: HIGH]
- [x] #22
- [x] testing: user testing and integrated testing and unit testing [priority: HIGH]
- [x] #19
- [x] find the linkways and take pictures of them in NUS. [priority: MEDIUM]
- [x] #21
- [x] #23
- [x] bus routespage to add the bus routes [priority: HIGH]

**Comment by applepiofmyeye** [comment]
###extra stuff! -- should b v fast
- [ ] ui of autocomplete -- pressing button is abit weird -- only 3/4 gets the "pressed" effect
- [ ] the frlist should be in reverse order -- last added to the front of the list 
- [ ]
