### ISSUE TITLE
TODO for milestone #3

### ISSUE THREAD

**Issue by applepiofmyeye** [applepiofmyeye/NUSWhere#17]
- [x] update poster to include intro, system design, evaluation and conclusion.
- [x] video to show the final product as intended
- [x] dev plan to include the plan till august
- [x] conduct user testing x 4? irl
- [x] entity relationship diagram 
- [x] #20
- [x]  quote the source at the motivations section
- [x] briefly mention how firebase is integration happened (not just simply a user guide)
- [x] rendering the line that is drawn between two locations (more to explain)
- [x]  problems encountered can just say unable to finish by milestone 3 because...
- [x] modify program flow, shape: diamond is if else, parallelogram is for key in user input. can look into activity diagram for modification.
- [x]  non trivial test cases (something that is not too obv like would we want to accept special characters?) can consider how we want people to use our app, are there any restrictions for the users
- [x] beautify react native explanation (choose because we can have more time to work for our application)
- [x] need to show attempt of nearestbusstops (click into it but can dont show any real timing, can hardcode for example, can just state the bus frequency for each buses)
- [x] favorite list bug sorted out
